require('dotenv').config({
  path: `./config/env/.env.${process.env.ENV}`,
})

const { ENV, FE_BASE_URL, WP_BASE_URL } = process.env

// https://v3.nuxtjs.org/api/configuration/nuxt.config
export default defineNuxtConfig({
  runtimeConfig: {
    public: {
      IS_DEV: ENV == 'dev',
      FE_BASE_URL: FE_BASE_URL,
      WP_REFRESH_VALUE: Date.now(),
      WP_BASE_URL: WP_BASE_URL,
      WP_AUTH_API_BASE_URL: `${WP_BASE_URL}/wp-json/jwt-auth/v1`,
      WP_REST_API_BASE_URL: `${WP_BASE_URL}/wp-json/wp/v2`,
    },
  },
  app: {
    head: {
      htmlAttrs: {
        lang: 'en',
      },
      charset: 'utf-8',
      viewport: 'width=device-width, initial-scale=1',
      title: 'Nuxt Wordpress CMS',
      meta: [
        {
          name: 'description',
          content:
            'Frontend powered by Vue, statically generated by Nuxt js and hosted in Vercel. Headless CMS by Wordpress hosted in SiteGround.',
        },
        { name: 'og:locale', content: 'en' },
        { name: 'description', content: 'Homepage description' },
        { name: 'og:locale', content: 'en' },
        { name: 'og:title', content: 'Homepage' },
        { name: 'og:description', content: 'Homepage description' },
        { name: 'og:type', content: 'website' },
        { name: 'og:url', content: FE_BASE_URL },
        { name: 'og:image', content: '' },
        { name: 'twitter:card', content: 'summary' },
        { name: 'twitter:title', content: 'Homepage' },
        { name: 'twitter:description', content: 'Homepage description' },
        { name: 'twitter:image', content: '' },
      ],
      script: [],
    },
  },
  modules: ['@nuxtjs/sitemap', '@nuxtjs/robots', '@pinia/nuxt'],
  vite: {
    css: {
      preprocessorOptions: {
        scss: {
          additionalData: '@use "@/assets/css/_main.scss" as *;',
        },
      },
    },
  },
})
